# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# trentbarton_buses:
#   stop: 688
  
http:
  base_url: !secret full_base_url

homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/recordings
    - /tmp
    - /config/www/recordings/front
    - /config/www/recordings/back
    - /config/assets
    - /captures

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret full_base_url

discovery:

ios:

api:

octoprint:
  host: !secret octoprint_ip
  api_key: !secret octoprint_api_key
  bed: true
  number_of_tools: 1
  sensors:
    monitored_conditions:
      - 'Current State'
      - 'Temperatures'
      - 'Job Percentage'
      - 'Time Elapsed'
      - 'Time Remaining'

media_player:
  - platform: plex
  - platform: androidtv
    name: Bedroom TV
    host: !secret bedroom_tv_ip
  - platform: androidtv
    name: Living Room TV
    host: !secret livingroom_tv_ip

google:
  client_id: !secret google_client_id_cal
  client_secret: !secret google_secret_cal

# calendar:
#   - platform: caldav
#     url: !secret private_calander_tv_shows

plex:
  host: !secret plex_ip
  port: 32400
  token: !secret plex_token
  ssl: false
  verify_ssl: false
  media_player:
    use_episode_art: true
    show_all_controls: false

nzbget:
  host: !secret nzbget_ip
  username: !secret nzbget_user
  password: !secret nzbget_pass

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

stream:


zoneminder:
  host: !secret zoneminder_ip
  path: /zm/
  ssl: true
  verify_ssl: false

camera:
  - platform: zoneminder

folder_watcher:
  - folder: /config/www/recordings/front
  - folder: /config/www/recordings/back

binary_sensor:
  - platform: workday
    country: UK

remote:
  - platform: broadlink
    host: !secret broadlink_mini_ip
    mac: 'C8:F7:42:16:E5:19'
    name: bedroom_broadlink

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 250415414
      - -250415414
      - 805671767

notify:
  - name: notify_joe
    platform: telegram
    chat_id: 805671767
  - name: notify_joe_and_sophie
    platform: telegram
    chat_id: -250415414
  - platform: nfandroidtv
    name: Bedroom Tv
    host: 192.168.1.110

sonoff:
  username: !secret sonoff_username
  password: !secret sonoff_password
  scan_interval: 60
  grace_period: 600

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  tls_insecure: true
  port: 1883
  discovery: true
  discovery_prefix: homeassistant

namecheapdns:
  host: home
  domain: !secret main_domain
  password: !secret namecheap_dns_api_key 

zone:
  - name: Home
    latitude: !secret home_lat
    longitude: !secret home_lon
    radius: 600
    icon: mdi:home
    

panel_iframe:
  router:
    title: 'Dashboard'
    url: !secret dashboard_url

light: !include lights.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetimes.yaml
input_boolean: !include input_booleans.yaml
input_number: !include input_numbers.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
